version: '3.9'

services:
  postgres:
    image: postgres:16.1
    environment:
      POSTGRES_USER: university_admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: university
    ports:
      - 5432:5432
    networks:
      - flask-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - flask-network
    ports:
      - 5050:5050

networks:
  flask-network:
